import { Kysely, sql } from "kysely";


export function up(db: Kysely<unknown>) {
  return db.schema.createTable('loinc')
    .addColumn('code', 'varchar(255)', col => col.notNull().primaryKey())
    .addColumn('component', 'text')
    .addColumn('property', 'varchar(255)')
    .addColumn('time_aspect', 'varchar(255)')
    .addColumn('system', 'varchar(255)')
    .addColumn('scale_type', 'varchar(255)')
    .addColumn('method_type', 'varchar(255)')
    .addColumn('class', 'varchar(255)')
    .addColumn('version_last_changed', 'varchar(255)')
    .addColumn('change_type', 'varchar(255)')
    .addColumn('definition_description', 'text')
    .addColumn('status', 'varchar(255)')
    .addColumn('consumer_name', 'varchar(255)')
    .addColumn('class_type', 'varchar(255)')
    .addColumn('formula', 'varchar(255)')
    .addColumn('example_answers', 'varchar(255)')
    .addColumn('survey_question_text', 'varchar(255)')
    .addColumn('survey_question_source', 'varchar(255)')
    .addColumn('units_required', 'boolean', col => col.notNull())
    .addColumn('related_names2', sql`varchar(50)[]`)
    .addColumn('short_name', 'varchar(255)')
    .addColumn('order_obs', 'varchar(255)')
    .addColumn('hl7_field_subfield_id', 'varchar(255)')
    .addColumn('external_copyright_notice', 'varchar(255)')
    .addColumn('example_units', 'varchar(255)')
    .addColumn('long_common_name', 'text')
    .addColumn('example_ucum_units', 'varchar(255)')
    .addColumn('status_reason', 'varchar(255)')
    .addColumn('status_text', 'varchar(255)')
    .addColumn('change_reason_public', 'varchar(255)')
    .addColumn('common_test_rank', 'varchar(255)')
    .addColumn('common_order_rank', 'varchar(255)')
    .addColumn('hl7_attachment_structure', 'varchar(255)')
    .addColumn('external_copyright_link', 'varchar(255)')
    .addColumn('panel_type', 'varchar(255)')
    .addColumn('ask_at_order_entry', 'varchar(255)')
    .addColumn('associated_observations', 'varchar(255)')
    .addColumn('version_first_released', 'varchar(255)')
    .addColumn('valid_hl7_attachment_request', 'varchar(255)')
    .addColumn('display_name', 'text')
    .execute()
}

export function down(db: Kysely<unknown>) {
  return db.schema.dropTable('loinc').execute()
}
