version: '3.4'
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: vha_postgres
    environment:
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: vha_dev
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U runner -d vha_dev']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mylocalnetwork
    volumes:
      - ./db:/db

  adminer:
    image: adminer
    container_name: vha_adminer
    ports:
      - '8888:8080'
    networks:
      - mylocalnetwork

networks:
  mylocalnetwork:
    driver: bridge
