import db from './db/db.ts'
import * as models$patient_occupations from './db/models/patient_occupations.ts'
import * as models$examinations from './db/models/examinations.ts'
import * as models$inventory from './db/models/inventory.ts'
import * as models$conversations from './db/models/conversations.ts'
import * as models$waiting_room from './db/models/waiting_room.ts'
import models$devices from './db/models/devices.ts'
import * as models$doctor from './db/models/doctor.ts'
import models$consumables from './db/models/consumables.ts'
import * as models$regulators from './db/models/regulators.ts'
import * as models$pharmacies from './db/models/pharmacies.ts'
import * as models$patient_conditions from './db/models/patient_conditions.ts'
import * as models$patient_symptoms from './db/models/patient_symptoms.ts'
import * as models$addresses from './db/models/addresses.ts'
import * as models$patient_lifestyle from './db/models/patient_lifestyle.ts'
import * as models$send_to from './db/models/send_to.ts'
import * as models$family from './db/models/family.ts'
import * as models$employment from './db/models/employment.ts'
import * as models$organizations from './db/models/organizations.ts'
import * as models$patient_encounters from './db/models/patient_encounters.ts'
import * as models$patients from './db/models/patients.ts'
import * as models$health_workers from './db/models/health_workers.ts'
import * as models$providers from './db/models/providers.ts'
import * as models$diagnoses from './db/models/diagnoses.ts'
import * as models$conditions from './db/models/conditions.ts'
import * as models$icd10 from './db/models/icd10.ts'
import * as models$snomed from './db/models/snomed.ts'
import * as models$appointments from './db/models/appointments.ts'
import * as models$mailing_list from './db/models/mailing_list.ts'
import * as models$manufactured_medications from './db/models/manufactured_medications.ts'
import * as models$prescription_medications from './db/models/prescription_medications.ts'
import * as models$head_to_toe_assessments from './db/models/head_to_toe_assessments.ts'
import * as models$doctor_reviews from './db/models/doctor_reviews.ts'
import models$procurers from './db/models/procurers.ts'
import * as models$pharmacy_employment from './db/models/pharmacy_employment.ts'
import * as models$nurse_registration_details from './db/models/nurse_registration_details.ts'
import * as models$patient_allergies from './db/models/patient_allergies.ts'
import * as models$pharmacists from './db/models/pharmacists.ts'
import * as models$prescriptions from './db/models/prescriptions.ts'
import * as models$patient_age from './db/models/patient_age.ts'
import * as models$drugs from './db/models/drugs.ts'
import * as models$patient_measurements from './db/models/patient_measurements.ts'
import * as models$media from './db/models/media.ts'
import * as models$findings from './db/models/findings.ts'
import * as models$patient_intake from './db/models/patient_intake.ts'
import * as models$sessions from './db/models/sessions.ts'
import * as models$_base from './db/models/_base.ts'
import * as migrations$20240323134041_patient_examinations from './db/migrations/20240323134041_patient_examinations.ts'
import * as migrations$20240215045435_icd10_tables from './db/migrations/20240215045435_icd10_tables.ts'
import * as migrations$20240108094046_patient_kin from './db/migrations/20240108094046_patient_kin.ts'
import * as migrations$20230707204541_health_worker_invitees from './db/migrations/20230707204541_health_worker_invitees.ts'
import * as migrations$20240618013760_pharmacist_whatsapp_associations from './db/migrations/20240618013760_pharmacist_whatsapp_associations.ts'
import * as migrations$20240126001827_encounter_steps from './db/migrations/20240126001827_encounter_steps.ts'
import * as migrations$20240430115100_pharmacists from './db/migrations/20240430115100_pharmacists.ts'
import * as migrations$20230721032340_add_appointment_request_media from './db/migrations/20230721032340_add_appointment_request_media.ts'
import * as migrations$20231129161929_patient_condition_medications from './db/migrations/20231129161929_patient_condition_medications.ts'
import * as migrations$20230101144040_organization from './db/migrations/20230101144040_organization.ts'
import * as migrations$20230101130000_postgis from './db/migrations/20230101130000_postgis.ts'
import * as migrations$20241029001738_diagnoses_collaboration from './db/migrations/20241029001738_diagnoses_collaboration.ts'
import * as migrations$20230622222222_appointments from './db/migrations/20230622222222_appointments.ts'
import * as migrations$20240201191913_patient_family from './db/migrations/20240201191913_patient_family.ts'
import * as migrations$20240618013759_patient_whatsapp_associations from './db/migrations/20240618013759_patient_whatsapp_associations.ts'
import * as migrations$20230717010755_doctor_registration_details from './db/migrations/20230717010755_doctor_registration_details.ts'
import * as migrations$20230101120000_updated_at from './db/migrations/20230101120000_updated_at.ts'
import * as migrations$20231228192406_patient_occupations from './db/migrations/20231228192406_patient_occupations.ts'
import * as migrations$20231218200916_allergies from './db/migrations/20231218200916_allergies.ts'
import * as migrations$20230127000000_employment from './db/migrations/20230127000000_employment.ts'
import * as migrations$20240218201816_symptoms from './db/migrations/20240218201816_symptoms.ts'
import * as migrations$20231117190808_conditions_tables from './db/migrations/20231117190808_conditions_tables.ts'
import * as migrations$20230629185250_patient_nearest_organizations_view from './db/migrations/20230629185250_patient_nearest_organizations_view.ts'
import * as migrations$20240705162545_prescriptions from './db/migrations/20240705162545_prescriptions.ts'
import * as migrations$20240825021342_diagnoses from './db/migrations/20240825021342_diagnoses.ts'
import * as migrations$20231207211637_family from './db/migrations/20231207211637_family.ts'
import * as migrations$20230101130001_trgm from './db/migrations/20230101130001_trgm.ts'
import * as migrations$20230101134040_snomed from './db/migrations/20230101134040_snomed.ts'
import * as migrations$20231020200227_mailing_list from './db/migrations/20231020200227_mailing_list.ts'
import * as migrations$20240701221001_pharmacy_tables from './db/migrations/20240701221001_pharmacy_tables.ts'
import * as migrations$20230129024002_whatsapp_conversation from './db/migrations/20230129024002_whatsapp_conversation.ts'
import * as migrations$20230717010754_nurse_registration_details from './db/migrations/20230717010754_nurse_registration_details.ts'
import * as migrations$20240124215007_intake_steps from './db/migrations/20240124215007_intake_steps.ts'
import * as migrations$20240814213854_manufactured_medication_recalls from './db/migrations/20240814213854_manufactured_medication_recalls.ts'
import * as migrations$20240103071516_patient_age_view from './db/migrations/20240103071516_patient_age_view.ts'
import * as migrations$20230101110000_utc from './db/migrations/20230101110000_utc.ts'
import * as migrations$20230101130002_fuzzystrmatch from './db/migrations/20230101130002_fuzzystrmatch.ts'
import * as migrations$20240101201154_measurements from './db/migrations/20240101201154_measurements.ts'
import * as migrations$20230128000000_inventory_tables from './db/migrations/20230128000000_inventory_tables.ts'
import * as migrations$20231221224916_waiting_room from './db/migrations/20231221224916_waiting_room.ts'
import * as migrations$20230125000000_health_workers from './db/migrations/20230125000000_health_workers.ts'
import * as migrations$20230126000000_address_tables from './db/migrations/20230126000000_address_tables.ts'
import * as migrations$20230124000000_media from './db/migrations/20230124000000_media.ts'
import * as migrations$20230101134041_examinations_tables from './db/migrations/20230101134041_examinations_tables.ts'
import * as migrations$20230101130003_generate_create_table_statement from './db/migrations/20230101130003_generate_create_table_statement.ts'
import * as migrations$20230128000002_medication_tables from './db/migrations/20230128000002_medication_tables.ts'
import * as migrations$20231128184405_patient_conditions from './db/migrations/20231128184405_patient_conditions.ts'
import * as migrations$20230101144039_address from './db/migrations/20230101144039_address.ts'
import * as migrations$20240212213855_patient_lifestyle from './db/migrations/20240212213855_patient_lifestyle.ts'
import * as migrations$20230127000001_patients from './db/migrations/20230127000001_patients.ts'
import * as migrations$20240314193153_doctor_reviews from './db/migrations/20240314193153_doctor_reviews.ts'
import * as migrations$20230125000001_regulators from './db/migrations/20230125000001_regulators.ts'
import util$capitalize from './util/capitalize.ts'
import util$isArguments from './util/isArguments.ts'
import util$selfUrl from './util/selfUrl.ts'
import util$timeToMin from './util/timeToMin.ts'
import * as util$uuid from './util/uuid.ts'
import * as util$pdfUtils from './util/pdfUtils.ts'
import * as util$date from './util/date.ts'
import * as util$groupBy from './util/groupBy.ts'
import * as util$path from './util/path.ts'
import util$set from './util/set.ts'
import * as util$spinner from './util/spinner.ts'
import util$debounce from './util/debounce.ts'
import * as util$name from './util/name.ts'
import util$sortBy from './util/sortBy.ts'
import * as util$inBackground from './util/inBackground.ts'
import * as util$searchPage from './util/searchPage.ts'
import * as util$jsonSearchHandler from './util/jsonSearchHandler.ts'
import util$deepRemoveHoles from './util/deepRemoveHoles.ts'
import util$isDate from './util/isDate.ts'
import util$sample from './util/sample.ts'
import util$words from './util/words.ts'
import * as util$pluralize from './util/pluralize.ts'
import * as util$haveNames from './util/haveNames.ts'
import util$isBoolean from './util/isBoolean.ts'
import * as util$delay from './util/delay.ts'
import util$last from './util/last.ts'
import * as util$take from './util/take.ts'
import * as util$collectSorted from './util/collectSorted.ts'
import * as util$resultify from './util/resultify.ts'
import util$arraysEqual from './util/arraysEqual.ts'
import * as util$isNumber from './util/isNumber.ts'
import util$internal$unicodeWords from './util/internal/unicodeWords.ts'
import util$internal$isPrototype from './util/internal/isPrototype.ts'
import util$internal$getTag from './util/internal/getTag.ts'
import * as util$matchActiveLink from './util/matchActiveLink.ts'
import * as util$promiseProps from './util/promiseProps.ts'
import * as util$assertEnum from './util/assertEnum.ts'
import util$zip from './util/zip.ts'
import util$pick from './util/pick.ts'
import * as util$pad from './util/pad.ts'
import util$isLength from './util/isLength.ts'
import util$shuffle from './util/shuffle.ts'
import * as util$uniq from './util/uniq.ts'
import util$hrefFromCtx from './util/hrefFromCtx.ts'
import util$isArrayLike from './util/isArrayLike.ts'
import * as util$assertAllUniqueBy from './util/assertAllUniqueBy.ts'
import * as util$capLengthAt from './util/capLengthAt.ts'
import * as util$combineAsyncIterables from './util/combineAsyncIterables.ts'
import util$permutations from './util/permutations.ts'
import * as util$allergyList from './util/allergyList.ts'
import util$compact from './util/compact.ts'
import util$isValidLocationString from './util/isValidLocationString.ts'
import util$deepOmit from './util/deepOmit.ts'
import util$isObjectLike from './util/isObjectLike.ts'
import * as util$validators from './util/validators.ts'
import util$range from './util/range.ts'
import * as util$parseForm from './util/parseForm.ts'
import util$redirect from './util/redirect.ts'
import * as util$cls from './util/cls.ts'
import * as util$bindAll from './util/bindAll.ts'
import util$parseJSON from './util/parseJSON.ts'
import * as util$assertOr from './util/assertOr.ts'
import * as util$replaceParams from './util/replaceParams.ts'
import * as util$zimbabweanDemographics from './util/zimbabweanDemographics.ts'
import * as util$trigram from './util/trigram.ts'
import * as util$assertAll from './util/assertAll.ts'
import util$flatten from './util/flatten.ts'
import * as util$units from './util/units.ts'
import * as util$assertAllPriorStepsCompleted from './util/assertAllPriorStepsCompleted.ts'
import util$debounceDefer from './util/debounceDefer.ts'
import * as util$command from './util/command.ts'
import util$partition from './util/partition.ts'
import * as util$parseCsv from './util/parseCsv.ts'
import * as util$responses from './util/responses.ts'
import util$memoize from './util/memoize.ts'
import util$isEmpty from './util/isEmpty.ts'
import * as util$inParallel from './util/inParallel.ts'
import * as util$getParam from './util/getParam.ts'
import * as util$isString from './util/isString.ts'
import util$omit from './util/omit.ts'
import * as util$alerts from './util/alerts.ts'
import routes$index from './routes/index.tsx'
import routes$loading_test from './routes/loading-test.tsx'
import routes$app from './routes/app.tsx'
import routes$volunteer from './routes/volunteer.tsx'
import routes$waitlist from './routes/waitlist.tsx'
import routes$app$patients$patient_id from './routes/app/patients/[patient_id].tsx'
import routes$app$patients$patient_id$review from './routes/app/patients/[patient_id]/review.tsx'
import * as routes$app$patients$patient_id$intake$address from './routes/app/patients/[patient_id]/intake/address.tsx'
import * as routes$app$patients$patient_id$intake$family from './routes/app/patients/[patient_id]/intake/family.tsx'
import * as routes$app$patients$patient_id$intake$conditions from './routes/app/patients/[patient_id]/intake/conditions.tsx'
import * as routes$app$patients$patient_id$intake$lifestyle from './routes/app/patients/[patient_id]/intake/lifestyle.tsx'
import * as routes$app$patients$patient_id$intake$history from './routes/app/patients/[patient_id]/intake/history.tsx'
import * as routes$app$patients$patient_id$intake$personal from './routes/app/patients/[patient_id]/intake/personal.tsx'
import * as routes$app$patients$patient_id$intake$occupation from './routes/app/patients/[patient_id]/intake/occupation.tsx'
import * as routes$app$patients$patient_id$intake$_middleware from './routes/app/patients/[patient_id]/intake/_middleware.tsx'
import * as routes$app$patients$patient_id$intake$summary from './routes/app/patients/[patient_id]/intake/summary.tsx'
import routes$app$patients$patient_id$profile$visits from './routes/app/patients/[patient_id]/profile/visits.tsx'
import routes$app$patients$patient_id$profile$review from './routes/app/patients/[patient_id]/profile/review.tsx'
import routes$app$patients$patient_id$profile$profile from './routes/app/patients/[patient_id]/profile/profile.tsx'
import routes$app$patients$patient_id$profile$history from './routes/app/patients/[patient_id]/profile/history.tsx'
import routes$app$patients$patient_id$profile$orders from './routes/app/patients/[patient_id]/profile/orders.tsx'
import * as routes$app$patients$patient_id$profile$_middleware from './routes/app/patients/[patient_id]/profile/_middleware.tsx'
import routes$app$patients$patient_id$profile$summary from './routes/app/patients/[patient_id]/profile/summary.tsx'
import routes$app$patients$patient_id$profile$appointments from './routes/app/patients/[patient_id]/profile/appointments.tsx'
import * as routes$app$patients$patient_id$avatar from './routes/app/patients/[patient_id]/avatar.tsx'
import * as routes$app$patients$patient_id$review$diagnosis from './routes/app/patients/[patient_id]/review/diagnosis.tsx'
import * as routes$app$patients$patient_id$review$prescriptions from './routes/app/patients/[patient_id]/review/prescriptions.tsx'
import * as routes$app$patients$patient_id$review$clinical_notes from './routes/app/patients/[patient_id]/review/clinical_notes.tsx'
import * as routes$app$patients$patient_id$review$orders from './routes/app/patients/[patient_id]/review/orders.tsx'
import * as routes$app$patients$patient_id$review$_middleware from './routes/app/patients/[patient_id]/review/_middleware.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$diagnoses from './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnoses.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$examinations from './routes/app/patients/[patient_id]/encounters/[encounter_id]/examinations.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$vitals from './routes/app/patients/[patient_id]/encounters/[encounter_id]/vitals.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$head_to_toe_assessment from './routes/app/patients/[patient_id]/encounters/[encounter_id]/head_to_toe_assessment.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$referral from './routes/app/patients/[patient_id]/encounters/[encounter_id]/referral.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$close_visit from './routes/app/patients/[patient_id]/encounters/[encounter_id]/close_visit.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$prescriptions from './routes/app/patients/[patient_id]/encounters/[encounter_id]/prescriptions.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$diagnostic_tests from './routes/app/patients/[patient_id]/encounters/[encounter_id]/diagnostic_tests.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$clinical_notes from './routes/app/patients/[patient_id]/encounters/[encounter_id]/clinical_notes.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$symptoms from './routes/app/patients/[patient_id]/encounters/[encounter_id]/symptoms.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$orders from './routes/app/patients/[patient_id]/encounters/[encounter_id]/orders.tsx'
import * as routes$app$patients$patient_id$encounters$encounter_id$_middleware from './routes/app/patients/[patient_id]/encounters/[encounter_id]/_middleware.tsx'
import routes$app$patients$patient_id$encounters$encounter_id from './routes/app/patients/[patient_id]/encounters/[encounter_id].tsx'
import routes$app$patients$patient_id$intake from './routes/app/patients/[patient_id]/intake.tsx'
import * as routes$app$patients$patient_id$_middleware from './routes/app/patients/[patient_id]/_middleware.tsx'
import * as routes$app$organizations$organization_id$inventory from './routes/app/organizations/[organization_id]/inventory.tsx'
import routes$app$organizations$organization_id$waiting_room from './routes/app/organizations/[organization_id]/waiting_room.tsx'
import * as routes$app$organizations$organization_id$patients from './routes/app/organizations/[organization_id]/patients.tsx'
import * as routes$app$organizations$organization_id$employees from './routes/app/organizations/[organization_id]/employees.tsx'
import * as routes$app$organizations$organization_id$waiting_room$add from './routes/app/organizations/[organization_id]/waiting_room/add.tsx'
import * as routes$app$organizations$organization_id$register from './routes/app/organizations/[organization_id]/register.tsx'
import * as routes$app$organizations$organization_id$_middleware from './routes/app/organizations/[organization_id]/_middleware.ts'
import * as routes$app$organizations$organization_id$register$step from './routes/app/organizations/[organization_id]/register/[step].tsx'
import * as routes$app$organizations$organization_id$inventory$add_device from './routes/app/organizations/[organization_id]/inventory/add_device.tsx'
import * as routes$app$organizations$organization_id$inventory$add_procurer from './routes/app/organizations/[organization_id]/inventory/add_procurer.tsx'
import routes$app$organizations$organization_id$inventory$history from './routes/app/organizations/[organization_id]/inventory/history.tsx'
import * as routes$app$organizations$organization_id$inventory$add_consumable from './routes/app/organizations/[organization_id]/inventory/add_consumable.tsx'
import * as routes$app$organizations$organization_id$inventory$consume from './routes/app/organizations/[organization_id]/inventory/consume.tsx'
import * as routes$app$organizations$organization_id$inventory$add_medicine from './routes/app/organizations/[organization_id]/inventory/add_medicine.tsx'
import * as routes$app$organizations$organization_id$employees$health_worker_id$approve from './routes/app/organizations/[organization_id]/employees/[health_worker_id]/approve.tsx'
import * as routes$app$organizations$organization_id$employees$health_worker_id$media$media_id from './routes/app/organizations/[organization_id]/employees/[health_worker_id]/media/[media_id].tsx'
import * as routes$app$organizations$organization_id$employees$invite from './routes/app/organizations/[organization_id]/employees/invite.tsx'
import routes$app$organizations$organization_id$employees$health_worker_id from './routes/app/organizations/[organization_id]/employees/[health_worker_id].tsx'
import routes$app$organizations$organization_id from './routes/app/organizations/[organization_id].tsx'
import * as routes$app$surgeries from './routes/app/surgeries.tsx'
import * as routes$app$calendar$appointments$appointment_id$media$media_id from './routes/app/calendar/appointments/[appointment_id]/media/[media_id].tsx'
import * as routes$app$calendar$appointments$schedule from './routes/app/calendar/appointments/schedule.tsx'
import * as routes$app$calendar$appointments$id from './routes/app/calendar/appointments/[id].tsx'
import * as routes$app$calendar$availability from './routes/app/calendar/availability.tsx'
import * as routes$app$patients from './routes/app/patients.tsx'
import * as routes$app$employees from './routes/app/employees.tsx'
import routes$app$chart from './routes/app/chart.tsx'
import * as routes$app$consumables from './routes/app/consumables.tsx'
import * as routes$app$manufactured_medications from './routes/app/manufactured_medications.tsx'
import routes$app$unauthorized from './routes/app/unauthorized.tsx'
import routes$app$icd10_search from './routes/app/icd10_search.tsx'
import * as routes$app$devices from './routes/app/devices.tsx'
import * as routes$app$_middleware from './routes/app/_middleware.ts'
import * as routes$app$drugs from './routes/app/drugs.tsx'
import * as routes$app$conditions from './routes/app/conditions.tsx'
import * as routes$app$snomed$concepts from './routes/app/snomed/concepts.ts'
import * as routes$app$snomed$allergies from './routes/app/snomed/allergies.ts'
import routes$app$calendar from './routes/app/calendar.tsx'
import * as routes$app$organizations from './routes/app/organizations.tsx'
import routes$app$insufficient_permissions from './routes/app/insufficient_permissions.tsx'
import * as routes$app$icd10 from './routes/app/icd10.tsx'
import * as routes$app$symptoms from './routes/app/symptoms.tsx'
import * as routes$app$pending_approval from './routes/app/pending_approval.tsx'
import * as routes$app$procurers from './routes/app/procurers.tsx'
import * as routes$app$providers from './routes/app/providers.tsx'
import * as routes$app$media$uuid from './routes/app/media/[uuid].tsx'
import * as routes$login from './routes/login.tsx'
import * as routes$chatbot$incoming_whatsapp from './routes/chatbot/incoming-whatsapp.ts'
import routes$schedule_demo from './routes/schedule-demo.tsx'
import * as routes$interest from './routes/interest.tsx'
import routes$partner from './routes/partner.tsx'
import * as routes$_middleware from './routes/_middleware.ts'
import * as routes$regulator$medicines$medicine_id$recall from './routes/regulator/medicines/[medicine_id]/recall.tsx'
import routes$regulator$pharmacists from './routes/regulator/pharmacists.tsx'
import routes$regulator$medicines from './routes/regulator/medicines.tsx'
import * as routes$regulator$_middleware from './routes/regulator/_middleware.ts'
import routes$regulator$pharmacies from './routes/regulator/pharmacies.tsx'
import * as routes$regulator$pharmacies$add from './routes/regulator/pharmacies/add.tsx'
import routes$regulator$pharmacies$pharmacy_id from './routes/regulator/pharmacies/[pharmacy_id].tsx'
import routes$regulator$pharmacists$pharmacist_id from './routes/regulator/pharmacists/[pharmacist_id].tsx'
import * as routes$regulator$pharmacists$invite from './routes/regulator/pharmacists/invite.tsx'
import * as routes$regulator$pharmacists$pharmacist_id$revoke from './routes/regulator/pharmacists/[pharmacist_id]/revoke.tsx'
import * as routes$regulator$pharmacists$pharmacist_id$edit from './routes/regulator/pharmacists/[pharmacist_id]/edit.tsx'
import * as routes$logged_in from './routes/logged-in.tsx'
import * as routes$apply from './routes/apply.tsx'
import * as routes$role_entrypoint$logout from './routes/[role_entrypoint]/logout.ts'
import routes$privacy from './routes/privacy.tsx'
import * as routes$regulator from './routes/regulator.tsx'
import routes$tos from './routes/tos.tsx'
import routes$_404 from './routes/_404.tsx'
import routes$_app from './routes/_app.tsx'
import routes$prescriptions$prescription_id from './routes/prescriptions/[prescription_id].tsx'
import * as shared$examinations from './shared/examinations.ts'
import * as shared$measurements from './shared/measurements.ts'
import * as shared$diet from './shared/diet.ts'
import * as shared$eindex_icd10 from './shared/eindex_icd10.ts'
import * as shared$scheduling$makeAppointment from './shared/scheduling/makeAppointment.ts'
import * as shared$scheduling$cancelAppointment from './shared/scheduling/cancelAppointment.ts'
import * as shared$scheduling$availability from './shared/scheduling/availability.tsx'
import * as shared$scheduling$getProviderAvailability from './shared/scheduling/getProviderAvailability.ts'
import * as shared$notifications from './shared/notifications.ts'
import * as shared$startTrx from './shared/startTrx.ts'
import * as shared$body_parts from './shared/body_parts.ts'
import * as shared$family from './shared/family.ts'
import * as shared$cookie from './shared/cookie.ts'
import * as shared$medication from './shared/medication.ts'
import * as shared$review from './shared/review.ts'
import * as shared$encounter from './shared/encounter.ts'
import * as shared$intake from './shared/intake.ts'
import * as external_clients$slack from './external-clients/slack.ts'
import * as external_clients$snowstorm from './external-clients/snowstorm.ts'
import * as external_clients$redis from './external-clients/redis.ts'
import * as external_clients$google from './external-clients/google.ts'
import * as external_clients$snowstorm$Merges from './external-clients/snowstorm/Merges.ts'
import * as external_clients$snowstorm$Mrcm from './external-clients/snowstorm/Mrcm.ts'
import * as external_clients$snowstorm$Admin from './external-clients/snowstorm/Admin.ts'
import * as external_clients$snowstorm$Codesystems from './external-clients/snowstorm/Codesystems.ts'
import * as external_clients$snowstorm$WebRoute from './external-clients/snowstorm/WebRoute.ts'
import * as external_clients$snowstorm$Browser from './external-clients/snowstorm/Browser.ts'
import * as external_clients$snowstorm$Imports from './external-clients/snowstorm/Imports.ts'
import * as external_clients$snowstorm$ValidationMaintenance from './external-clients/snowstorm/ValidationMaintenance.ts'
import * as external_clients$snowstorm$Branch from './external-clients/snowstorm/Branch.ts'
import * as external_clients$snowstorm$MergeReviews from './external-clients/snowstorm/MergeReviews.ts'
import * as external_clients$snowstorm$Util from './external-clients/snowstorm/Util.ts'
import * as external_clients$snowstorm$Version from './external-clients/snowstorm/Version.ts'
import * as external_clients$snowstorm$Branches from './external-clients/snowstorm/Branches.ts'
import * as external_clients$snowstorm$Multisearch from './external-clients/snowstorm/Multisearch.ts'
import * as external_clients$snowstorm$http_client from './external-clients/snowstorm/http-client.ts'
import * as external_clients$snowstorm$Reviews from './external-clients/snowstorm/Reviews.ts'
import * as external_clients$snowstorm$Exports from './external-clients/snowstorm/Exports.ts'
import * as external_clients$whatsapp from './external-clients/whatsapp.ts'
import components$patients$AppointmentDetail from './components/patients/AppointmentDetail.tsx'
import components$patients$DetailedCard from './components/patients/DetailedCard.tsx'
import components$patients$View from './components/patients/View.tsx'
import components$patients$intake$HistoryForm from './components/patients/intake/HistoryForm.tsx'
import components$patients$intake$PreExistingConditionsForm from './components/patients/intake/PreExistingConditionsForm.tsx'
import components$patients$intake$AddressForm from './components/patients/intake/AddressForm.tsx'
import * as components$patients$intake$Summary from './components/patients/intake/Summary.tsx'
import components$patients$profile$PatientHistory from './components/patients/profile/PatientHistory.tsx'
import components$patients$profile$PatientProfile from './components/patients/profile/PatientProfile.tsx'
import components$patients$profile$PatientSummary from './components/patients/profile/PatientSummary.tsx'
import components$patients$Table from './components/patients/Table.tsx'
import components$patients$EmptyState from './components/patients/EmptyState.tsx'
import components$calendar$Appointment from './components/calendar/Appointment.tsx'
import components$calendar$ScheduleForm from './components/calendar/ScheduleForm.tsx'
import components$calendar$Calendar from './components/calendar/Calendar.tsx'
import * as components$calendar$AppointmentsCalendar from './components/calendar/AppointmentsCalendar.tsx'
import components$calendar$EmptyState from './components/calendar/EmptyState.tsx'
import components$calendar$Appointments from './components/calendar/Appointments.tsx'
import components$waiting_room$View from './components/waiting_room/View.tsx'
import components$waiting_room$Table from './components/waiting_room/Table.tsx'
import components$waiting_room$EmptyState from './components/waiting_room/EmptyState.tsx'
import components$library$SideBySide from './components/library/SideBySide.tsx'
import * as components$library$Steps from './components/library/Steps.tsx'
import * as components$library$CircularImage from './components/library/CircularImage.tsx'
import components$library$Pagination from './components/library/Pagination.tsx'
import * as components$library$Tabs from './components/library/Tabs.tsx'
import * as components$library$Card from './components/library/Card.tsx'
import * as components$library$Container from './components/library/Container.tsx'
import components$library$FlyoutMenu from './components/library/FlyoutMenu.tsx'
import * as components$library$Person from './components/library/Person.tsx'
import * as components$library$HeaderHeight from './components/library/HeaderHeight.ts'
import * as components$library$Label from './components/library/Label.tsx'
import components$library$modals$Warning from './components/library/modals/Warning.tsx'
import * as components$library$AdditionalInfo from './components/library/AdditionalInfo.tsx'
import * as components$library$Description from './components/library/Description.tsx'
import * as components$library$HiddenInput from './components/library/HiddenInput.tsx'
import components$library$Avatar from './components/library/Avatar.tsx'
import components$library$Layout from './components/library/Layout.tsx'
import * as components$library$icons$SeekingTreatment from './components/library/icons/SeekingTreatment.tsx'
import * as components$library$icons$Medicines from './components/library/icons/Medicines.tsx'
import * as components$library$icons$vitals from './components/library/icons/vitals.tsx'
import * as components$library$icons$GoogleMeet from './components/library/icons/GoogleMeet.tsx'
import * as components$library$icons$progress from './components/library/icons/progress.tsx'
import * as components$library$icons$AddPatient from './components/library/icons/AddPatient.tsx'
import * as components$library$icons$MakeAppointment from './components/library/icons/MakeAppointment.tsx'
import * as components$library$icons$Pharmacies from './components/library/icons/Pharmacies.tsx'
import * as components$library$icons$PickedRequestReview from './components/library/icons/PickedRequestReview.tsx'
import * as components$library$icons$heroicons$solid from './components/library/icons/heroicons/solid.tsx'
import * as components$library$icons$heroicons$outline from './components/library/icons/heroicons/outline.tsx'
import * as components$library$icons$heroicons$mini from './components/library/icons/heroicons/mini.tsx'
import * as components$library$icons$DeclareEmergency from './components/library/icons/DeclareEmergency.tsx'
import * as components$library$icons$PickedDeclareEmergency from './components/library/icons/PickedDeclareEmergency.tsx'
import * as components$library$icons$RequestReview from './components/library/icons/RequestReview.tsx'
import * as components$library$icons$FilledPlus from './components/library/icons/FilledPlus.tsx'
import * as components$library$icons$whatsapp from './components/library/icons/whatsapp.tsx'
import * as components$library$icons$Plussable from './components/library/icons/Plussable.tsx'
import * as components$library$icons$PickedMakeAppointments from './components/library/icons/PickedMakeAppointments.tsx'
import * as components$library$icons$BluetoothIcon from './components/library/icons/BluetoothIcon.tsx'
import * as components$library$icons$MakeAppointments from './components/library/icons/MakeAppointments.tsx'
import * as components$library$SearchResults from './components/library/SearchResults.tsx'
import * as components$library$Logo from './components/library/Logo.tsx'
import components$library$typography$PageHeader from './components/library/typography/PageHeader.tsx'
import components$library$typography$SectionHeader from './components/library/typography/SectionHeader.tsx'
import * as components$library$Header from './components/library/Header.tsx'
import components$library$Badge from './components/library/Badge.tsx'
import * as components$library$PlusButton from './components/library/PlusButton.tsx'
import * as components$library$DescriptionList from './components/library/DescriptionList.tsx'
import * as components$library$Sidebar from './components/library/Sidebar.tsx'
import components$library$Table from './components/library/Table.tsx'
import * as components$library$Button from './components/library/Button.tsx'
import * as components$library$EmptyState from './components/library/EmptyState.tsx'
import * as components$library$AdditionalDescription from './components/library/AdditionalDescription.tsx'
import * as components$library$HeroIconButton from './components/library/HeroIconButton.tsx'
import components$library$FormRow from './components/library/FormRow.tsx'
import components$library$Media from './components/library/Media.tsx'
import components$library$FormSection from './components/library/FormSection.tsx'
import * as components$library$Form from './components/library/Form.tsx'
import * as components$health_worker$nurse$invite$Steps from './components/health_worker/nurse/invite/Steps.tsx'
import components$health_worker$nurse$invite$NursePersonalForm from './components/health_worker/nurse/invite/NursePersonalForm.tsx'
import components$health_worker$nurse$invite$NurseProfessionalForm from './components/health_worker/nurse/invite/NurseProfessionalForm.tsx'
import components$health_worker$nurse$invite$NurseDocumentsForm from './components/health_worker/nurse/invite/NurseDocumentsForm.tsx'
import components$health_worker$DetailedCard from './components/health_worker/DetailedCard.tsx'
import components$health_worker$EmployeesTable from './components/health_worker/EmployeesTable.tsx'
import * as components$regulator$PharmaciesTable from './components/regulator/PharmaciesTable.tsx'
import components$regulator$PharmacyDetailedCard from './components/regulator/PharmacyDetailedCard.tsx'
import components$regulator$DetailedCard from './components/regulator/DetailedCard.tsx'
import components$regulator$PharmacistsTable from './components/regulator/PharmacistsTable.tsx'
import * as components$regulator$MedicinesTable from './components/regulator/MedicinesTable.tsx'
import components$regulator$InvitePharmacistForm from './components/regulator/InvitePharmacistForm.tsx'
import * as components$regulator$MedicinesSearch from './components/regulator/MedicinesSearch.tsx'
import components$inventory$MedicineForm from './components/inventory/MedicineForm.tsx'
import components$inventory$View from './components/inventory/View.tsx'
import components$inventory$DevicesTable from './components/inventory/DevicesTable.tsx'
import components$inventory$InventoryHistory from './components/inventory/InventoryHistory.tsx'
import components$inventory$MedicinesTable from './components/inventory/MedicinesTable.tsx'
import components$inventory$DeviceForm from './components/inventory/DeviceForm.tsx'
import components$inventory$ConsumablesTable from './components/inventory/ConsumablesTable.tsx'
import components$OnlineIndicator from './components/OnlineIndicator.tsx'
import * as components$landing_page$Hero from './components/landing-page/Hero.tsx'
import components$landing_page$ArrowLink from './components/landing-page/ArrowLink.tsx'
import * as components$landing_page$HealthWorkers from './components/landing-page/HealthWorkers.tsx'
import components$landing_page$HeroContents from './components/landing-page/HeroContents.tsx'
import * as components$landing_page$Team from './components/landing-page/Team.tsx'
import components$landing_page$Features from './components/landing-page/Features.tsx'
import components$landing_page$MedicalIconPattern from './components/landing-page/MedicalIconPattern.tsx'
import * as components$landing_page$Patients from './components/landing-page/Patients.tsx'
import * as components$landing_page$Testimonial from './components/landing-page/Testimonial.tsx'
import components$landing_page$home from './components/landing-page/home.tsx'
import * as components$landing_page$ScheduleADemo from './components/landing-page/ScheduleADemo.tsx'
import * as components$landing_page$Pattern from './components/landing-page/Pattern.tsx'
import components$landing_page$DemoVideoContainer from './components/landing-page/DemoVideoContainer.tsx'
import components$landing_page$partner_logos$usf from './components/landing-page/partner-logos/usf.tsx'
import components$landing_page$partner_logos$vcu from './components/landing-page/partner-logos/vcu.tsx'
import * as components$landing_page$Partners from './components/landing-page/Partners.tsx'
import components$landing_page$sections from './components/landing-page/sections.tsx'
import components$landing_page$SectionHeading from './components/landing-page/SectionHeading.tsx'
import * as components$landing_page$Research from './components/landing-page/Research.tsx'
import * as components$landing_page$Footer from './components/landing-page/Footer.tsx'
import components$landing_page$WifiPattern from './components/landing-page/WifiPattern.tsx'
import * as components$landing_page$FeatureGrid from './components/landing-page/FeatureGrid.tsx'
import components$landing_page$RadialPattern from './components/landing-page/RadialPattern.tsx'
import components$landing_page$DoctorImage from './components/landing-page/DoctorImage.tsx'
import * as components$landing_page$Introduction from './components/landing-page/Introduction.tsx'
import * as components$examinations$Category from './components/examinations/Category.tsx'
import * as components$examinations$Checklist from './components/examinations/Checklist.tsx'
import * as components$examinations$Form from './components/examinations/Form.tsx'
import components$prescriptions$PrescriptionDetail from './components/prescriptions/PrescriptionDetail.tsx'
import * as components$prescriptions$MedicationsTable from './components/prescriptions/MedicationsTable.tsx'
import islands$AddPharmacistSearch from './islands/AddPharmacistSearch.tsx'
import * as islands$vitals$Form from './islands/vitals/Form.tsx'
import islands$AddPharmacySearch from './islands/AddPharmacySearch.tsx'
import * as islands$AddDeviceSearch from './islands/AddDeviceSearch.tsx'
import * as islands$form$Listbox from './islands/form/Listbox.tsx'
import islands$form$unsaved_changes_warning from './islands/form/unsaved_changes_warning.tsx'
import * as islands$form$Inputs from './islands/form/Inputs.tsx'
import * as islands$form$buttons from './islands/form/buttons.tsx'
import * as islands$referral$Form from './islands/referral/Form.tsx'
import islands$nurse_registration_form from './islands/nurse-registration-form.tsx'
import islands$patient_intake$PersonalForm from './islands/patient-intake/PersonalForm.tsx'
import islands$availability_form from './islands/availability-form.tsx'
import * as islands$icd10$SearchSpecific from './islands/icd10/SearchSpecific.tsx'
import islands$SelectWithOther from './islands/SelectWithOther.tsx'
import islands$JobPost from './islands/JobPost.tsx'
import islands$SuccessMessage from './islands/SuccessMessage.tsx'
import islands$ReligionSelect from './islands/ReligionSelect.tsx'
import islands$ErrorMessage from './islands/ErrorMessage.tsx'
import islands$invites_form from './islands/invites-form.tsx'
import islands$past_medical_conditions$Condition from './islands/past-medical-conditions/Condition.tsx'
import islands$past_medical_conditions$Form from './islands/past-medical-conditions/Form.tsx'
import islands$waiting_room$AddPatientForm from './islands/waiting_room/AddPatientForm.tsx'
import * as islands$waiting_room$AddPatientSearch from './islands/waiting_room/AddPatientSearch.tsx'
import islands$FlyoutMenu from './islands/FlyoutMenu.tsx'
import islands$WarningMessage from './islands/WarningMessage.tsx'
import islands$Search from './islands/Search.tsx'
import islands$allergy$Search from './islands/allergy/Search.tsx'
import islands$allergy$Input from './islands/allergy/Input.tsx'
import islands$PersonSearch from './islands/PersonSearch.tsx'
import * as islands$file_preview_input from './islands/file-preview-input.tsx'
import islands$NationalIdInput from './islands/NationalIdInput.tsx'
import islands$AsyncSearch from './islands/AsyncSearch.tsx'
import islands$lifestyle$DietForm from './islands/lifestyle/DietForm.tsx'
import islands$lifestyle$AlcoholForm from './islands/lifestyle/AlcoholForm.tsx'
import islands$lifestyle$SexualActivityForm from './islands/lifestyle/SexualActivityForm.tsx'
import islands$lifestyle$SubstanceUseForm from './islands/lifestyle/SubstanceUseForm.tsx'
import islands$lifestyle$ExerciseForm from './islands/lifestyle/ExerciseForm.tsx'
import islands$lifestyle$SmokingForm from './islands/lifestyle/SmokingForm.tsx'
import islands$family$MaritalStatusSelect from './islands/family/MaritalStatusSelect.tsx'
import islands$family$PatientCohabitationSelect from './islands/family/PatientCohabitationSelect.tsx'
import islands$family$Guardian from './islands/family/Guardian.tsx'
import islands$family$NextOfKin from './islands/family/NextOfKin.tsx'
import islands$family$Dependent from './islands/family/Dependent.tsx'
import islands$family$RelationshipSelect from './islands/family/RelationshipSelect.tsx'
import islands$family$FamilyTypeSelect from './islands/family/FamilyTypeSelect.tsx'
import islands$family$Form from './islands/family/Form.tsx'
import islands$AddressForm from './islands/AddressForm.tsx'
import * as islands$LifestyleForm from './islands/LifestyleForm.tsx'
import islands$diagnoses$FormRow from './islands/diagnoses/FormRow.tsx'
import islands$diagnoses$Form from './islands/diagnoses/Form.tsx'
import islands$ConditionSearch from './islands/ConditionSearch.tsx'
import * as islands$SendTo$SelectedPatient from './islands/SendTo/SelectedPatient.tsx'
import * as islands$SendTo$List from './islands/SendTo/List.tsx'
import * as islands$SendTo$Icons from './islands/SendTo/Icons.tsx'
import * as islands$SendTo$Header from './islands/SendTo/Header.tsx'
import * as islands$SendTo$Sidebar from './islands/SendTo/Sidebar.tsx'
import * as islands$SendTo$ListItem from './islands/SendTo/ListItem.tsx'
import * as islands$SendTo$RequestRadioButtons from './islands/SendTo/RequestRadioButtons.tsx'
import * as islands$SendTo$Button from './islands/SendTo/Button.tsx'
import * as islands$SendTo$Form from './islands/SendTo/Form.tsx'
import islands$regulator$PharmacistForm from './islands/regulator/PharmacistForm.tsx'
import islands$regulator$PharmacyForm from './islands/regulator/PharmacyForm.tsx'
import * as islands$manufactured_medication$Search from './islands/manufactured_medication/Search.tsx'
import islands$manufactured_medication$Input from './islands/manufactured_medication/Input.tsx'
import islands$pre_existing_conditions$Comorbidity from './islands/pre-existing-conditions/Comorbidity.tsx'
import islands$pre_existing_conditions$Condition from './islands/pre-existing-conditions/Condition.tsx'
import islands$pre_existing_conditions$Form from './islands/pre-existing-conditions/Form.tsx'
import * as islands$AddConsumableSearch from './islands/AddConsumableSearch.tsx'
import * as islands$AddRemove from './islands/AddRemove.tsx'
import * as islands$BaseOption from './islands/BaseOption.tsx'
import * as islands$patient_drawer$FindingsList from './islands/patient-drawer/FindingsList.tsx'
import * as islands$patient_drawer$Drawer from './islands/patient-drawer/Drawer.tsx'
import * as islands$patient_drawer$FindingsListItemSchema from './islands/patient-drawer/FindingsListItemSchema.ts'
import * as islands$patient_drawer$FindingsListItem from './islands/patient-drawer/FindingsListItem.tsx'
import * as islands$Notifications from './islands/Notifications.tsx'
import islands$patient_cards from './islands/patient-cards.tsx'
import islands$ProvidersSelect from './islands/ProvidersSelect.tsx'
import * as islands$timer from './islands/timer.tsx'
import islands$inventory$Consumable from './islands/inventory/Consumable.tsx'
import islands$inventory$ConsumeForm from './islands/inventory/ConsumeForm.tsx'
import islands$inventory$ProcurerForm from './islands/inventory/ProcurerForm.tsx'
import islands$inventory$DeviceSearch from './islands/inventory/DeviceSearch.tsx'
import islands$landing_page$NavBar from './islands/landing-page/NavBar.tsx'
import * as islands$landing_page$MHIDotsLogo from './islands/landing-page/MHIDotsLogo.tsx'
import * as islands$examinations$ChecklistItem from './islands/examinations/ChecklistItem.tsx'
import * as islands$examinations$BodySiteSelect from './islands/examinations/BodySiteSelect.tsx'
import * as islands$examinations$New from './islands/examinations/New.tsx'
import * as islands$examinations$Dialog from './islands/examinations/Dialog.tsx'
import islands$symptoms$Section from './islands/symptoms/Section.tsx'
import * as islands$symptoms$DurationInput from './islands/symptoms/DurationInput.tsx'
import islands$symptoms$Input from './islands/symptoms/Input.tsx'
import islands$Occupation19 from './islands/Occupation19.tsx'
import * as islands$Menu from './islands/Menu.tsx'
import islands$Occupation0_18 from './islands/Occupation0-18.tsx'
import islands$NationalIdInputCheckbox from './islands/NationalIdInputCheckbox.tsx'
import * as islands$CloseButton from './islands/CloseButton.tsx'
import * as islands$ErrorListener from './islands/ErrorListener.tsx'
import islands$major_surgeries$Surgery from './islands/major-surgeries/Surgery.tsx'
import islands$major_surgeries$Form from './islands/major-surgeries/Form.tsx'
import islands$medication$Input from './islands/medication/Input.tsx'
import * as islands$NearestHealthCare from './islands/NearestHealthCare.tsx'
import islands$drug$Search from './islands/drug/Search.tsx'
import islands$drug$Input from './islands/drug/Input.tsx'
import islands$SurgerySearch from './islands/SurgerySearch.tsx'
import * as islands$SparklinesExample from './islands/SparklinesExample.tsx'
import islands$DemoVideo from './islands/DemoVideo.tsx'
import * as islands$prescriptions$ScheduleInput from './islands/prescriptions/ScheduleInput.tsx'
import * as islands$prescriptions$ScheduleRow from './islands/prescriptions/ScheduleRow.tsx'
import * as islands$prescriptions$MedicationInput from './islands/prescriptions/MedicationInput.tsx'
import islands$prescriptions$Form from './islands/prescriptions/Form.tsx'
import * as islands$prescriptions$MedicationRow from './islands/prescriptions/MedicationRow.tsx'
import islands$useAsyncSearch from './islands/useAsyncSearch.tsx'
import islands$summary$DescriptionRow from './islands/summary/DescriptionRow.tsx'
import islands$BackLink from './islands/BackLink.tsx'
import islands$OrganizationSearch from './islands/OrganizationSearch.tsx'

let m = await models$icd10.searchSymptoms(db, undefined, { limit: Infinity })

//
m.forEach((foo) => {
  external_clients$snowstorm.searchConcepts({
    term: foo.description,
  })
  foo.description
})
let foo = m[0]
let z = await external_clients$snowstorm.searchConcepts({
  term: foo.description,
})

let y = await external_clients$snowstorm.searchConcepts({
  term: 'Abnormal weight gain',
  termActive: true,
  activeFilter: true,
})

y = (await external_clients$snowstorm.searchConcepts({
  term: 'Symptoms and signs concerning food and fluid intake',
  termActive: true,
  activeFilter: true,
})).data.items

// Just get the SNOMED codes and use esl to get the descendants
