import { type Config } from 'tailwindcss'
import formsPlugin from '@tailwindcss/forms'
import headlessuiPlugin from '@headlessui/tailwindcss'

// export default {
//   content: ['{routes,islands,components}/**/*.{ts,tsx}'],
//   theme: {
//     fontFamily: {
//       sans: ['Inter', 'sans-serif'],
//       ubuntu: ['Ubuntu', 'sans-serif'],
//       display: ['Cabinet Grotesk', 'sans-serif'],
//     },
//     extend: {
//       borderRadius: {
//         '4xl': '2rem',
//         '5xl': '3rem',
//         '6xl': '5rem',
//       },
//       strokeWidth: {
//         '3': '3px',
//       },
//     },
//     fontSize: {
//       xs: ['0.75rem', { lineHeight: '1rem' }],
//       sm: ['0.875rem', { lineHeight: '1.5rem' }],
//       base: ['1rem', { lineHeight: '2rem' }],
//       lg: ['1.125rem', { lineHeight: '2rem' }],
//       xl: ['1.25rem', { lineHeight: '2rem' }],
//       '2xl': ['1.375rem', { lineHeight: '2rem' }],
//       '3xl': ['1.5rem', { lineHeight: '2rem' }],
//       '4xl': ['2rem', { lineHeight: '2.5rem' }],
//       '5xl': ['3.5rem', { lineHeight: '1' }],
//       '6xl': ['4rem', { lineHeight: '1' }],
//       '7xl': ['4.5rem', { lineHeight: '1' }],
//       '8xl': ['6rem', { lineHeight: '1' }],
//       '9xl': ['8rem', { lineHeight: '1' }],
//     },
//   },
//   plugins: [formsPlugin, headlessuiPlugin],
// } satisfies Config

export default {
  content: ['{routes,islands,components}/**/*.{ts,tsx}'],
  plugins: [formsPlugin, headlessuiPlugin],
  theme: {
    extend: {
      colors: {
        'Primary Color/Indigo/100': 'rgba(224, 231, 255, 1)',
        'Primary Color/Indigo/200': 'rgba(199, 210, 254, 1)',
        'Primary Color/Indigo/300': 'rgba(165, 180, 252, 1)',
        'Primary Color/Indigo/400': 'rgba(129, 140, 248, 1)',
        'Primary Color/Indigo/500': 'rgba(99, 102, 241, 1)',
        'Primary Color/Indigo/600': 'rgba(79, 70, 229, 1)',
        'Primary Color/Indigo/700': 'rgba(67, 56, 202, 1)',
        'Primary Color/Indigo/800': 'rgba(55, 48, 163, 1)',
        'Primary Color/Indigo/900': 'rgba(49, 46, 129, 1)',
        'Primary Color/Indigo/1000': 'rgba(36, 31, 103, 1)',
        'Primary Color/Netural/000': 'rgba(255, 255, 255, 1)',
        'Primary Color/Netural/50': 'rgba(249, 250, 251, 1)',
        'Primary Color/Netural/100': 'rgba(243, 244, 246, 1)',
        'Primary Color/Netural/200': 'rgba(229, 231, 235, 1)',
        'Primary Color/Netural/300': 'rgba(209, 213, 219, 1)',
        'Primary Color/Netural/400': 'rgba(149, 156, 169, 1)',
        'Primary Color/Netural/500': 'rgba(107, 114, 128, 1)',
        'Primary Color/Netural/600': 'rgba(75, 85, 99, 1)',
        'Primary Color/Netural/700': 'rgba(55, 65, 81, 1)',
        'Primary Color/Netural/800': 'rgba(31, 41, 55, 1)',
        'Primary Color/Netural/900': 'rgba(17, 24, 39, 1)',
        'Primary Colors/on-brand': 'rgba(NaN, NaN, NaN, undefined)',
        'Primary Colors/primary': 'rgba(NaN, NaN, NaN, undefined)',
        'Primary Colors/secondary': 'rgba(NaN, NaN, NaN, undefined)',
        'Primary Colors/tertiary': 'rgba(NaN, NaN, NaN, undefined)',
        'Accent Colors/blue/blue-bg': 'rgba(219, 234, 254, 1)',
        'Accent Colors/blue/blue-text*icon': 'rgba(30, 64, 175, 1)',
        'Accent Colors/teal/teal-bg': 'rgba(204, 251, 241, 1)',
        'Accent Colors/teal/teal-text*icon': 'rgba(17, 94, 89, 1)',
        'Accent Colors/orange/orange-bg': 'rgba(255, 237, 213, 1)',
        'Accent Colors/orange/orange-text*icon': 'rgba(194, 65, 12, 1)',
        'Accent Colors/orange/orange-status': 'rgba(249, 115, 22, 1)',
        'Accent Colors/pink/pink-bg': 'rgba(252, 231, 243, 1)',
        'Accent Colors/pink/pink-text*icon': 'rgba(157, 23, 77, 1)',
        'Accent Colors/purple/purple-bg': 'rgba(243, 232, 255, 1)',
        'Accent Colors/purple/purple-text*icon': 'rgba(107, 33, 168, 1)',
        'Success Colors/grey/grey-bg': 'rgba(NaN, NaN, NaN, undefined)',
        'Success Colors/grey/grey-text*icon': 'rgba(NaN, NaN, NaN, undefined)',
        'Success Colors/grey/grey-status': 'rgba(NaN, NaN, NaN, undefined)',
        'Success Colors/yellow/yellow-bg': 'rgba(254, 249, 195, 1)',
        'Success Colors/yellow/yellow-text*icon': 'rgba(133, 77, 14, 1)',
        'Success Colors/yellow/yellow-status': 'rgba(250, 204, 21, 1)',
        'Success Colors/green/green-bg': 'rgba(220, 252, 231, 1)',
        'Success Colors/green/green-text*icon': 'rgba(22, 101, 52, 1)',
        'Success Colors/green/green-status': 'rgba(22, 163, 74, 1)',
        'Success Colors/green/green-input': 'rgba(240, 253, 250, 1)',
        'Success Colors/red/red-bg': 'rgba(254, 226, 226, 1)',
        'Success Colors/red/red-text*icon': 'rgba(153, 27, 27, 1)',
        'Success Colors/red/red-status': 'rgba(220, 38, 38, 1)',
        'Success Colors/red/red-flagged': 'rgba(248, 113, 113, 1)',
        'Success Colors/red/red-input': 'rgba(254, 242, 242, 1)',
        'Netural Colors/primary': 'rgba(NaN, NaN, NaN, undefined)',
        'Netural Colors/secondary': 'rgba(NaN, NaN, NaN, undefined)',
        'Netural Colors/tertiary': 'rgba(NaN, NaN, NaN, undefined)',
        'Netural Colors/disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/Border*line': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/primary': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/primary-hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/base': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/base-hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/secondary-hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/secondary': 'rgba(NaN, NaN, NaN, undefined)',
        'Background/line-2': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/default': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/focus': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/pressed': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/text-dark': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Primary/text-light': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/default': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/focus': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/pressed': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/text-light': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/text-disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Secondary/text-dark': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/default': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/focus': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/pressed': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/text-light': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/text-disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Tertiary/text-dark': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/text-default': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/text-hover': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/text-pressed': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/text-disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/text-focus': 'rgba(NaN, NaN, NaN, undefined)',
        'Button/Hyderlink/bt-text-disabled': 'rgba(NaN, NaN, NaN, undefined)',
        'Primary Color/Indigo/50': 'rgba(238, 242, 255, 1)',
        'Button/Tertiary/bg-border': 'rgba(NaN, NaN, NaN, undefined)',
        'Primary Color/Netural/Color': 'rgba(255, 255, 255, 1)',
      },
      fontFamily: {
        'H/1-24px': [
          'Inter',
        ],
        'H/2-20px': [
          'Inter',
        ],
        'H/3-18px': [
          'Inter',
        ],
        'H/4-16px': [
          'Inter',
        ],
        'H/5-14px': [
          'Inter',
        ],
        'P/20px/Regular': [
          'Inter',
        ],
        'P/20px/Medium': [
          'Inter',
        ],
        'P/20px/Semi Bold': [
          'Inter',
        ],
        'P/20px/Bold': [
          'Inter',
        ],
        'P/18px/Regular': [
          'Inter',
        ],
        'P/18px/Medium': [
          'Inter',
        ],
        'P/18px/Semi Bold': [
          'Inter',
        ],
        'P/18px/Bold': [
          'Inter',
        ],
        'P/16px/Regular': [
          'Inter',
        ],
        'P/16px/Medium': [
          'Inter',
        ],
        'P/16px/Semi Bold': [
          'Inter',
        ],
        'P/16px/Bold': [
          'Inter',
        ],
        'P/14px/Regular': [
          'Inter',
        ],
        'P/14px/Medium': [
          'Inter',
        ],
        'P/14px/Semi Bold': [
          'Inter',
        ],
        'P/14px/Bold': [
          'Inter',
        ],
        'P/12px/Regular': [
          'Inter',
        ],
        'P/12px/Medium': [
          'Inter',
        ],
        'P/12px/Semi Bold': [
          'Inter',
        ],
        'P/12px/Bold': [
          'Inter',
        ],
        'P/12px/Italic': [
          'Inter',
        ],
      },
      fontSize: {
        'H/1-24px': '24px',
        'H/2-20px': '20px',
        'H/3-18px': '18px',
        'H/4-16px': '16px',
        'H/5-14px': '14px',
        'P/20px/Regular': '20px',
        'P/20px/Medium': '20px',
        'P/20px/Semi Bold': '20px',
        'P/20px/Bold': '20px',
        'P/18px/Regular': '18px',
        'P/18px/Medium': '18px',
        'P/18px/Semi Bold': '18px',
        'P/18px/Bold': '18px',
        'P/16px/Regular': '16px',
        'P/16px/Medium': '16px',
        'P/16px/Semi Bold': '16px',
        'P/16px/Bold': '16px',
        'P/14px/Regular': '14px',
        'P/14px/Medium': '14px',
        'P/14px/Semi Bold': '14px',
        'P/14px/Bold': '14px',
        'P/12px/Regular': '12px',
        'P/12px/Medium': '12px',
        'P/12px/Semi Bold': '12px',
        'P/12px/Bold': '12px',
        'P/12px/Italic': '12px',
      },
      boxShadow: {
        'Dropbox - Menu': '0px 8px 15px rgba(0, 0, 0, 0.08)',
      },
    },
  },
} satisfies Config
