;; Page 19 - Seizures/Fits
(task
  "Check for urgent seizure conditions"
  adult
  (clinical_finding (snomed_concept "Seizure" "finding"))
  (check_for
    (clinical_finding (snomed_concept "Injury of head" "disorder") (qualifier (snomed_concept "Current" "qualifier value")))
    (clinical_finding (snomed_concept "Unconscious" "finding"))
    (clinical_finding (snomed_concept "Hypoglycemia" "disorder"))
    (clinical_finding (snomed_concept "Alcohol use disorder" "disorder"))
		(clinical_finding ( snomed_concept “Substance use disorder” (disorder))
		(clinical_finding ( snomed_concept “Headache” (finding))
		(clinical_finding ( snomed_concept “Seizure” (finding))
		(clinical_finding ( snomed_concept “Stiff neck” (finding))
		(clinical_finding ( snomed_concept “Purpuric rash (disorder))
		(clinical_finding ( snomed_concept “History of travel with high risk of exposure to communicable disease” (situation) “Malaria” (disorder))
		(clinical_finding ( snomed_concept “Headache” (finding) “New” (qualifier value))
		(clinical_finding ( snomed_concept “Frequent headache” (finding))
		(clinical_finding ( snomed_concept “Headache” (finding) “Worse” (qualifier value))
		(clinical_finding ( snomed_concept “Human immunodeficiency virus infection” (disorder))
		(clinical_finding ( snomed_concept “Epilepsy” (disorder))
		(> (clinical_finding ( snomed_concept “Decreased level of consciousness” (finding) “After” (attribute) “Seizure” (finding) 
		(clinical_finding ( snomed_concept “Muscle weakness” (finding) “New” (qualifier value) “Sudden” (qualifier value) “Asymmetry” (qualifier value))
		(clinical_finding ( snomed_concept “Numbness” (finding))
		(clinical_finding ( snomed_concept “Difficulty talking” (finding))
		(clinical_finding ( snomed_concept “Visual disturbance” (disorder))
		(clinical_finding ( snomed_concept “Pregnancy” (finding)
		(clinical_finding ( snomed_concept “Postpartum period, 7 days” (finding)
		)
	)
)