;; Headache ⇢ 30
(finding_site_findings
  "Head"
  (finding_site_structure (snomed_concept "Head structure" "body structure"))
  (excluding_structures
    (snomed_concept "Structure of eye proper" "body structure")
    (snomed_concept "Face structure" "body structure")
    (snomed_concept "Ear structure" "body structure")
    (snomed_concept "Nasal structure" "body structure")
    (snomed_concept "Structure of mouth and/or pharynx" "body structure")
    (snomed_concept "Tooth, gum, and/or supporting structure" "body structure")
    (snomed_concept "Scalp structure" "body structure")
  )
  (clinical_findings
    (clinical_finding (snomed_concept "Headache" "finding"))
    (clinical_finding (snomed_concept "Headache" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")) (qualifier (snomed_concept "Severe (severity modifier)" "qualifier value")))
    (clinical_finding (snomed_concept "Headache" "finding") (qualifier (snomed_concept "Wakes up during night" "finding")))
    (clinical_finding (snomed_concept "Headache" "finding") (qualifier (snomed_concept "Symptom is continuous" "finding")))
    (clinical_finding (snomed_concept "Morning headache" "finding"))
    (clinical_finding (snomed_concept "Frequent headache" "finding"))
    (clinical_finding (snomed_concept "Frequent headache" "finding") (qualifier (snomed_concept "Worsening" "qualifier value")))
    (clinical_finding (snomed_concept "Decreased level of consciousness" "finding"))
    (clinical_finding (snomed_concept "Weakness of face muscles" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Muscle weakness of upper limb" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Weakness of muscle of lower limb" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Numbness of face" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Numbness of limbs" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Speech problem" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")))
    (clinical_finding (snomed_concept "Visual symptoms" "finding") (qualifier (snomed_concept "New" "qualifier value")))
    (clinical_finding (snomed_concept "Pain in eye" "finding") (qualifier (snomed_concept "New" "qualifier value")))
    (clinical_finding (snomed_concept "Dizziness" "finding") (qualifier (snomed_concept "Sudden onset" "qualifier value")) (qualifier (snomed_concept "Severe (severity modifier)" "qualifier value")))
    ;; Neck stiffness, drowsy/confused or purple/red rash
    (clinical_finding (snomed_concept "Stiff neck" "finding"))
    (clinical_finding (snomed_concept "Drowsy" "finding"))
    (clinical_finding (snomed_concept "Clouded consciousness" "finding"))
    (clinical_finding (snomed_concept "Purpuric rash" "disorder"))
    (clinical_finding (snomed_concept "Persistent vomiting" "disorder"))
    (clinical_finding (snomed_concept "Nausea" "finding") (qualifier (snomed_concept "Symptom is continuous" "finding")))
    (clinical_finding (snomed_concept "Nausea and vomiting" "disorder"))
    (clinical_finding (snomed_concept "Highly active antiretroviral therapy" "procedure"))
    (clinical_finding (snomed_concept "Seizure" "finding"))
    (clinical_finding (snomed_concept "Injury of head" "disorder") (qualifier (snomed_concept "Recent" "qualifier value")))
    (clinical_finding (snomed_concept "Anisocoria" "disorder"))
    (clinical_finding (snomed_concept "Visual disturbance" "disorder"))
    ;; Fever and body pain, or recent common cold
    (clinical_finding (snomed_concept "Fever" "finding"))
    (clinical_finding (snomed_concept "Generalized aches and pains" "finding"))
    (clinical_finding (snomed_concept "Common cold" "disorder") (qualifier (snomed_concept "Recent" "qualifier value")))
    (clinical_finding (snomed_concept "Nasal discharge" "finding") (qualifier (snomed_concept "Thick" "qualifier value")))
    (clinical_finding (snomed_concept "Posterior rhinorrhea" "disorder") (qualifier (snomed_concept "Thick" "qualifier value")))
  )
)
