;;Page 12 – Observation Post Vaccination 
(task
"Worrying symptoms or adverse reactions post vaccination"
	(adult
		(clinical_finding (snomed_concept “Administration of vaccine to produce active immunity (procedure)
		AND
		(clinical_finding (snomed_concept “Observes (attribute) minute (qualifier value) 15  After (attribute)
		OR
		(clinical_finding (snomed_concept “Observes (attribute) minute (qualifier value) 30 After (attribute)
			(check_for
				(clinical_finding (snomed_concept “Allergic disposition (finding) Severe (severity modifier) (qualifier value) Known (qualifier value)
				(clinical_finding (snomed_concept “Syncope” (finding))
				(clinical_finding (snomed_concept “Feeling faint” (finding))
				(clinical_finding (snomed_concept “Lightheadedness” (finding))
				(clinical_finding (snomed_concept “Dizziness” (finding))
				(clinical_finding (snomed_concept “Sensation of being warm” (finding))
				(clinical_finding (snomed_concept “Sensation of being cold” (finding))
				(clinical_finding (snomed_concept “Sweating” (finding))
				(clinical_finding (snomed_concept “Palpitations” (finding))
				(clinical_finding (snomed_concept “Blurring of visual image” (finding))
				(clinical_finding (snomed_concept “Dim vision” (disorder))
				(clinical_finding (snomed_concept “Decreased hearing” (finding))
				(clinical_finding (snomed_concept “Pallor of skin of face” (finding))
				(clinical_finding (snomed_concept “Eruption of skin” (disorder))
					(clinical_finding (snomed_concept “Isolated” (qualifier value))
					(clinical_finding (snomed_concept “Raised” (qualifier value))
					(clinical_finding (snomed_concept “Red color” (qualifier value)
				(clinical_finding (snomed_concept “Itching” (finding))
				(clinical_finding (snomed_concept “Wheal” (finding))
(clinical_finding (snomed_concept “Urticaria” (disorder))
(clinical_finding (snomed_concept “Generalized rash” (disorder))
				(clinical_finding (snomed_concept “Swelling around eyes” (finding))
				(clinical_finding (snomed_concept “Lip swelling” (finding) “Both lips” (body structure))
				(clinical_finding (snomed_concept “Tongue swelling” (finding))
				(clinical_finding (snomed_concept “Facial swelling” (finding))
				(clinical_finding (snomed_concept “Localized swelling of bilateral hands” (finding))
				(clinical_finding (snomed_concept “Swelling of bilateral feet” (finding))
				(clinical_finding (snomed_concept “Low blood pressure” (disorder))
				(clinical_finding (snomed_concept “Nasal congestion” (finding))
				(clinical_finding (snomed_concept “Wheezing” (finding))
				(clinical_finding (snomed_concept “Cough” (finding))
				(clinical_finding (snomed_concept “Tightness in throat” (finding))
				(clinical_finding (snomed_concept “Stridor” (finding))
				(clinical_finding (snomed_concept “Dyspnea” (finding))
				(clinical_finding (snomed_concept “Respiratory distress” (finding))
				(clinical_finding (snomed_concept “Hoarse” (finding))
				(<measurement (clinical_finding (snomed_concept “Hemoglobin saturation with oxygen” (observable entity) “Percent” (property) (qualifier value) 92))
				(clinical_finding (snomed_concept “Difficulty swallowing” (finding))
				(clinical_finding (snomed_concept “Dribbling from mouth” (finding))
				(clinical_finding (snomed_concept “Nausea” (finding))
				(clinical_finding (snomed_concept “Vomiting” (disorder))
				(clinical_finding (snomed_concept “Diarrhea” (finding))
				(clinical_finding (snomed_concept “Stomach cramps” (finding))
		)
	)
)



