// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/common-symptoms-modifiers.ts
import { FindingRelatedModifiers } from '../types.ts'

export default {
  'Nasal discharge': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Discharge" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Nasal structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Fever': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Above reference range" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Body temperature" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Cough': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Respiratory tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Respiratory function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Sore throat': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of pharynx and/or larynx" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Headache': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Head structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Severe (severity modifier)" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Sudden onset" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Fatigue': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Energy / stamina" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dyspnea': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of respiratory system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Ease of respiration" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Sudden" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Nausea': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Upper gastrointestinal tract structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Vomiting': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Gastrointestinal tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Digestive system function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Diarrhea': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of digestive system" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Watery" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Dizziness': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Muscle pain': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Skeletal muscle structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Insect bite': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Superficial bite wound" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Bite of insect" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Backache': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of posterior region of trunk" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Severe (severity modifier)" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Constipation': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Intestinal structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Altered" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Bowel action" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': true,
  },
} as Record<string, FindingRelatedModifiers>
