// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/common-symptoms-modifiers.ts
import { FindingRelatedModifiers } from '../types.ts'

export default {
  'Nasal discharge': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Associated morphology',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Discharge',
          'category': 'morphologic abnormality',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Nasal structure',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Fever': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Has interpretation',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Above reference range',
          'category': 'qualifier value',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Body temperature',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Cough': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Respiratory tract structure',
          'category': 'body structure',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Respiratory function',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Sore throat': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Structure of pharynx and/or larynx',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Headache': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Head structure',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Sudden onset',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Severe (severity modifier)',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
    ],
  },
  'Fatigue': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Energy / stamina',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Dyspnea': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Structure of respiratory system',
          'category': 'body structure',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Ease of respiration',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Sudden',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
    ],
  },
  'Nausea': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Upper gastrointestinal tract structure',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Vomiting': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Gastrointestinal tract structure',
          'category': 'body structure',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Digestive system function',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Diarrhea': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Structure of digestive system',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Watery',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
    ],
  },
  'Dizziness': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
  },
  'Muscle pain': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Skeletal muscle structure',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
  'Insect bite': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Associated morphology',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Superficial bite wound',
          'category': 'morphologic abnormality',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Due to',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Bite of insect',
          'category': 'event',
        },
      },
    ],
    'relevant_qualifiers': [
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Recent',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
    ],
  },
  'Backache': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Structure of posterior region of trunk',
          'category': 'body structure',
        },
      },
    ],
    'relevant_qualifiers': [
      {
        'atom': 'qualifier',
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Severe (severity modifier)',
          'category': 'qualifier value',
        },
        'qualifiers': [],
      },
    ],
  },
  'Constipation': {
    'predefined_attributes': [
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Finding site',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Intestinal structure',
          'category': 'body structure',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Has interpretation',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Altered',
          'category': 'qualifier value',
        },
      },
      {
        'atom': 'attribute',
        'root_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Attribute',
          'category': 'attribute',
        },
        'specific_snomed_concept': {
          'atom': 'snomed_concept',
          'name': 'Interprets',
          'category': 'attribute',
        },
        'value': {
          'atom': 'snomed_concept',
          'name': 'Bowel action',
          'category': 'observable entity',
        },
      },
    ],
    'relevant_qualifiers': [],
  },
} as Record<string, FindingRelatedModifiers>
