// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/warning-signs-modifiers.ts
import { WarningSignKey } from './warning_signs.ts'
import { FindingRelatedModifiers } from '../types.ts'

export default {
  'Obstructed airway': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Obstruction" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Respiratory tract structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Cardiac arrest': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Cardiac conducting system structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Seizure': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Brain structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Burn Facial': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Face structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Burn Inhalation': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Inhalation of substance" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Respiratory tract structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Acute shortness of breath': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of respiratory system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Ease of respiration" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Sudden" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Chest pain': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Thoracic structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "At rest" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Unilateral" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Seizure - post ictal': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "After" "attribute") (snomed_concept "Seizure" "finding"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of nervous system" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Focal neurology': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Damage" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Brain structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Cerebrovascular system structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Burn Chemical': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Chemical burn" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Burning caused by caustic and corrosive substance" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Poisoning': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Aggression': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Behavior observable" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dislocation of larger joint': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Severe limb ischemia': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of artery of limb" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Known present" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Burn Circumferential': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Vomiting fresh blood': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Hemorrhage" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Upper gastrointestinal tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Digestive system function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Coughing blood': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Hemorrhage" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Respiratory tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Respiratory function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Stabbed neck': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Stab wound" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Neck structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Eye injury': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of eye proper" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Burn Over 20%': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Percent of body surface" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'High energy transfer': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Causative agent" "attribute") (snomed_concept "Physical force" "physical force"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Haemorrhage Uncontrolled': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Hemorrhage" "morphologic abnormality"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Compound Fracture': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Burn Moderate severity': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Pregnancy and abdominal trauma': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Pregnancy and abdominal pain': {
    'predefined_attributes': [
      {
        's_expression':
          '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of abdominopelvic cavity and/or content of abdominopelvic cavity and/or anterior abdominal wall" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Persistent vomiting': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Upper gastrointestinal tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Digestive system function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dislocation of finger': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Dislocation" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of joint of digit of hand" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dislocation of toe joint': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Dislocation" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of joint of toe" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Burn Other': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Haemorrhage Controlled': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Hemorrhage" "morphologic abnormality"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Closed fracture': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Fracture, closed" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Bone structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Abdominal pain': {
    'predefined_attributes': [
      {
        's_expression':
          '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of abdominopelvic cavity and/or content of abdominopelvic cavity and/or anterior abdominal wall" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Not breathing or Reported apnoea': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of respiratory system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Absent" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Respiration observable" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Obstructed breathing': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Obstruction" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Respiratory tract structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Central cyanosis (SPO2 less than 92%)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Blood oxygen concentration below reference range" "finding"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of skin and/or mucous membrane" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Abnormal" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Blue color" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Color of skin or mucosa" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Respiratory distress (Severe)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Clinical course" "attribute") (snomed_concept "Sudden onset AND/OR short duration" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of respiratory system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Ease of respiration" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Cold Hands': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Hand structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Body temperature" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Pulse weak & fast': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of cardiovascular system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Weak" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Pulse, function" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Pulse volume" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Capillary refill time (3 sec or more)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Peripheral blood vessel structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of capillary blood vessel" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Abnormal" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Capillary filling, function" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Peripheral blood flow" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Lethargic': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Energy observable" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Uncontrolled bleeding (not nose bleed)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Hemorrhage" "morphologic abnormality"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Convulsing or Immediately Post-Ictal not alert': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Brain structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'AVPU: responds only To Pain (P)': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'AVPU: Unresponsive (U)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "State of consciousness and awareness" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Confusion': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Clinical course" "attribute") (snomed_concept "Sudden onset AND/OR short duration" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Level of consciousness" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Mental alertness" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Diarrhoea or Vomiting': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Intestinal structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Upper gastrointestinal tract structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Altered" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Bowel action" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Digestive system function" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Watery" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Lethargy/ floppy infant': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Skeletal muscle structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Abnormally low" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Muscle tone" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Very sunken eyes': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of eye proper" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Skin pinch very slow (2 secs or more)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Skin structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Decreased" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Skin turgor" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Facial /Inhalation burn': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Face structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Hypoglycaemia recorded at any time': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of endocrine system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Below reference range" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Blood glucose concentration" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Glucose less than 3mmol/L': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Below reference range" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Glucose measurement, blood" "procedure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Purpuric rash': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Eruption" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Purpura" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Skin structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Excessive" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Pulsatile" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Tiny baby (Younger than 2 months)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Eating feeding / drinking observable" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Occurrence" "attribute") (snomed_concept "Neonatal" "qualifier value"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Inconsolable crying (Severe pain)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Long duration" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Crying" "observable entity"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Occurrence" "attribute") (snomed_concept "Infancy" "qualifier value"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Presenting complaint more sleepy than normal': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Decreased" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Level of consciousness" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Poisoning or overdose': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Focal neurology acute': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Damage" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Brain structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Cerebrovascular system structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Severe mechanism of injury': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Causative agent" "attribute") (snomed_concept "Physical force" "physical force"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Burn 10% or more (Circumferential, electrical, chemical)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Percent of body surface" "body structure"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Eye Injury': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of eye proper" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Fracture (Open or threatened limb)': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dislocation of larger joint (not finger or toe)': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Some respiratory distress': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of respiratory system" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Ease of respiration" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Some Dehydration (Diarrhoea or Diarrhoea and vomiting)': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Sunken eyes': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of eye proper" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Restless/ irritable': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Behavior observable" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Thirsty/decreased urine output': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Urinary system structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Below reference range" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Measure of urine output" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Dry mouth': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Salivary gland structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Crying without tears': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Crying" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Skin pinch slow (Less than 2 sec)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Skin structure" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Decreased" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Skin turgor" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Unable to drink /feed or vomit everything': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Has interpretation" "attribute") (snomed_concept "Unable" "qualifier value"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Interprets" "attribute") (snomed_concept "Ability to drink" "observable entity"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Malnutrition (Visible severe wasting)': {
    'predefined_attributes': [],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Malnutrition Oedema (pitting Oedema of both feet)': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Edema" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of left foot" "body structure"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of right foot" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Unwell child with known diabetes': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Structure of endocrine system" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
  'Any other burn less than 10%': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Burn injury" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Due to" "attribute") (snomed_concept "Traumatic event" "event"))',
      },
    ],
    'relevant_qualifiers': [
      {
        's_expression': '(qualifier (snomed_concept "Circumferential" "qualifier value"))',
      },
      {
        's_expression': '(qualifier (snomed_concept "Recent" "qualifier value"))',
      },
    ],
    'onset_required': false,
  },
  'Dislocation of finger or toe': {
    'predefined_attributes': [
      {
        's_expression': '(attribute (snomed_concept "Associated morphology" "attribute") (snomed_concept "Dislocation" "morphologic abnormality"))',
      },
      {
        's_expression': '(attribute (snomed_concept "Finding site" "attribute") (snomed_concept "Finger joint structure" "body structure"))',
      },
    ],
    'relevant_qualifiers': [],
    'onset_required': false,
  },
} as Record<WarningSignKey, FindingRelatedModifiers>
