name: Deploy Pharmacist Chatbot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vha-pharmacist-chatbot"
          heroku_email: "will@morehumaninternet.org"
          procfile: "worker: deno task chatbot"