name: Deploy Superadmin

on:
  push:
    branches:
      - medplum

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Use Dockerfile.vha-superadmin
        run: cp Dockerfile.vha-superadmin Dockerfile
      
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vha-superadmin"
          heroku_email: "will@morehumaninternet.org"
          docker_heroku_process_type: web
          usedocker: true
