name: Deploy Medplum Server

on:
  push:
    branches:
      - heroku_medplum_server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use medplum server Dockerfile
        run: cp Dockerfile.medplum-server Dockerfile

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vha-medplum-server"
          heroku_email: "will@morehumaninternet.org"
          usedocker: true