name: Deploy Pharmacist Chatbot

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Dockerfil.vha-pharmacist-chatbot
        run: cp Dockerfile.vha-pharmacist-chatbot Dockerfile
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vha-pharmacist-chatbot"
          heroku_email: "will@morehumaninternet.org"
          docker_heroku_process_type: worker
          usedocker: true