name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_STRING: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.4

      - name: Where am I?
        run: ls -la

      - name: Run lint
        run: deno lint

      - name: Run fmt --check
        run: deno fmt --check

      - name: Compile chatbot
        run: DENO_TLS_CA_STORE=system deno compile -A --target x86_64-unknown-linux-gnu --output binaries/chatbot chatbot/chatbot.ts