name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_STRING: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: vha_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check out PR branch
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.1
      
      - name: Run lint
        run: deno lint

      - name: Run fmt --check
        run: deno fmt --check
  
      - name: Test setup
        run: |
          echo "DATABASE_URL=postgres://testuser:testpw@localhost:5432/vha_test" > .env
          echo "SELF_URL=https://localhost:8000" >> .env
          echo "GOOGLE_MAPS_API_KEY=TEST_GOOGLE_MAPS_API_KEY" >> .env
          echo "SKIP_GOOGLE_MAPS=true" >> .env

      - name: Ensure migrations are in order
        run: deno run -A db/ensureMigrationsInOrder.ts
      
      - name: Migrate database
        run: deno task db:migrate:latest

      - name: Run tests
        run: deno task test

  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37.1

      - name: Compile chatbot
        run: deno task compile:chatbot

      - name: Compile token_refresher
        run: deno task compile:token_refresher

      - name: Compile web
        run: deno task compile:web
