name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_STRING: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpw
          POSTGRES_DB: vha_test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379/tcp

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.3

      - name: Run lint
        run: deno lint --ignore=landing-page/

      - name: Run fmt --check
        run: deno fmt --check

      - name: Test setup
        run: echo "DATABASE_URL=postgres://testuser:testpw@localhost:5432/vha_test" > .env

      - name: Run tests
        run: deno task test

      - name: Compile chatbot
        run: deno task compile:chatbot

      - name: Compile token_refresher
        run: deno task compile:token_refresher

      - name: Compile web
        run: deno task compile:web
