name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_STRING: "${{ github.run_number }}-${{ github.sha }}"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.3

      - name: Run lint
        run: deno lint --ignore=landing-page/

      - name: Run fmt --check
        run: deno fmt --check

      - name: Run tests
        run: deno test

      - name: Compile chatbot
        run: deno task compile:chatbot

      - name: Compile token_refresher
        run: deno task compile:token_refresher

      - name: Compile web
        run: deno task compile:web
