import { assert } from 'std/assert/assert.ts'
import db from '../../db/db.ts'
import { snomed_predefined_attributes } from '../../db/models/snomed_predefined_attributes.ts'
import { snomed_relevant_qualifiers } from '../../db/models/snomed_relevant_qualifiers.ts'
import { parseWithSchema } from '../../shared/s_expression.ts'
import { finding } from '../../shared/s_expression_schemas.ts'
import { pMap } from '../../util/inParallel.ts'
import fromEntries from '../../util/fromEntries.ts'
import { FindingRelatedModifiers } from '../../types.ts'
import { COMMON_SYMPTOMS_DEFS } from '../../shared/common_symptoms.ts'

async function commonSymptomsModifiers() {
  const entries = await pMap(COMMON_SYMPTOMS_DEFS, async (common_symptom): Promise<[typeof COMMON_SYMPTOMS_DEFS[number]['key'], FindingRelatedModifiers]> => {
    const node = parseWithSchema(common_symptom.clinical_finding_s_expression, finding)
    assert(node.specific_snomed_concept)
    const predefined_attributes = await snomed_predefined_attributes.findAll(db, { snomed_concept: node.specific_snomed_concept })
    const relevant_qualifiers = await snomed_relevant_qualifiers.findAll(db, { snomed_concept: node.specific_snomed_concept })
    return [common_symptom.key, {
      predefined_attributes,
      relevant_qualifiers,
    }]
  })

  return fromEntries(entries)
}

if (import.meta.main) {
  const common_symptomsmodifiers = await commonSymptomsModifiers()
  Deno.writeFileSync(
    'shared/common_symptoms_modifiers.ts',
    new TextEncoder().encode(
      `// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/common-symptoms-modifiers.ts
import { FindingRelatedModifiers } from '../types.ts'

export default ${JSON.stringify(common_symptomsmodifiers, null, 2)} as Record<string, FindingRelatedModifiers>
`,
    ),
  )
}
