import db from '../../db/db.ts'
import { snomed_onset_required } from '../../db/models/snomed_onset_required.ts'
import { snomed_predefined_attributes } from '../../db/models/snomed_predefined_attributes.ts'
import { snomed_relevant_qualifiers } from '../../db/models/snomed_relevant_qualifiers.ts'
import { pMap } from '../../util/inParallel.ts'
import fromEntries from '../../util/fromEntries.ts'
import { FindingRelatedModifiers } from '../../types.ts'
import { TASKS } from '../../shared/tasks.ts'
import { Lang } from '../../shared/s_expression_schemas.ts'
import { inverseSExpression } from '../../shared/s_expression_inverse.ts'

/*
  Modifiers for every finding any adult task checks for, keyed by the finding's specific
  concept, which is all the modifiers depend on. This is a superset of what
  shared/finding_site_signs.ts needs, so adding a page needs no regeneration
  unless it checks for a concept no other page does.
*/
async function findingSiteSignsModifiers() {
  const concepts = new Map<string, Lang['snomed_concept']>()
  for (const task of TASKS) {
    if (!task.ages.includes('adult')) continue
    const { value } = task.to_be_done
    if (!Array.isArray(value)) continue
    for (const node of value) {
      if (node.atom !== 'finding') continue
      concepts.set(inverseSExpression(node.specific_snomed_concept), node.specific_snomed_concept)
    }
  }

  const entries = await pMap([...concepts.entries()], async ([key, snomed_concept]): Promise<[string, FindingRelatedModifiers]> => {
    const predefined_attributes = await snomed_predefined_attributes.findAll(db, { snomed_concept })
    const relevant_qualifiers = await snomed_relevant_qualifiers.findAll(db, { snomed_concept })
    const onset_required = await snomed_onset_required.check(db, { snomed_concept })
    return [key, { predefined_attributes, relevant_qualifiers, onset_required }]
  })

  return fromEntries(entries.sort(([a], [b]) => a.localeCompare(b)))
}

if (import.meta.main) {
  const modifiers = await findingSiteSignsModifiers()
  Deno.writeFileSync(
    'shared/finding_site_signs_modifiers.ts',
    new TextEncoder().encode(
      `// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/finding-site-signs-modifiers.ts
import { FindingRelatedModifiers } from '../types.ts'

export default ${JSON.stringify(modifiers, null, 2)} as Record<string, FindingRelatedModifiers>
`,
    ),
  )
  await db.destroy()
}
