import { assert } from 'std/assert/assert.ts'
import db from '../../db/db.ts'
import { snomed_predefined_attributes } from '../../db/models/snomed_predefined_attributes.ts'
import { snomed_relevant_qualifiers } from '../../db/models/snomed_relevant_qualifiers.ts'
import { parseWithSchema } from '../../shared/s_expression.ts'
import { finding } from '../../shared/s_expression_schemas.ts'
import { WARNING_SIGN_DEFS, WarningSignKey } from '../../shared/warning_signs.ts'
import { pMap } from '../../util/inParallel.ts'
import fromEntries from '../../util/fromEntries.ts'
import { FindingRelatedModifiers } from '../../types.ts'

async function warningSignsModifiers() {
  const entries = await pMap(WARNING_SIGN_DEFS, async (warning_sign): Promise<[WarningSignKey, FindingRelatedModifiers]> => {
    const node = parseWithSchema(warning_sign.clinical_finding_s_expression, finding)
    assert(node.specific_snomed_concept)
    const predefined_attributes = await snomed_predefined_attributes.findAll(db, { snomed_concept: node.specific_snomed_concept })
    const relevant_qualifiers = await snomed_relevant_qualifiers.findAll(db, { snomed_concept: node.specific_snomed_concept })
    return [warning_sign.key, {
      predefined_attributes,
      relevant_qualifiers,
    }]
  })

  return fromEntries(entries)
}

if (import.meta.main) {
  const warning_signs_modifiers = await warningSignsModifiers()
  Deno.writeFileSync(
    'shared/warning_signs_modifiers.ts',
    new TextEncoder().encode(
      `// THIS FILE IS AUTOGENERATED. SEE scripts/data-munging/warning-signs-modifiers.ts
import { WarningSignKey } from './warning_signs.ts'
import { FindingRelatedModifiers } from '../types.ts'

export default ${JSON.stringify(warning_signs_modifiers, null, 2)} as Record<WarningSignKey, FindingRelatedModifiers>
`,
    ),
  )
}
